In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

Task 1: Identify Data Quality Issues

In [2]:
pd.set_option("display.max_columns", None)

df = pd.read_csv("Chocolate_Sales.csv")
df.head(10)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184
5,Van Tuxwell,India,Smooth Sliky Salty,06/06/2022,"$5,376.00",38
6,Oby Sorrel,UK,99% Dark & Pure,25/01/2022,"$13,685.00",176
7,Gunar Cockshoot,Australia,After Nines,24/03/2022,"$3,080.00",73
8,Jehu Rudeforth,New Zealand,50% Dark Bites,20/04/2022,"$3,990.00",59
9,Brien Boise,Australia,99% Dark & Pure,04/07/2022,"$2,835.00",102

In [3]:
df.dtypes

Sales Person     object
Country          object
Product          object
Date             object
Amount           object
Boxes Shipped     int64
dtype: object

In [7]:
df.isna().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

                                Date        Amount  Boxes Shipped
count                           3282   3282.000000    3282.000000
mean   2023-05-03 15:09:06.252284928   6030.338775     164.666971
min              2022-01-03 00:00:00      7.000000       1.000000
25%              2022-07-04 00:00:00   2521.495000      71.000000
50%              2023-05-11 00:00:00   5225.500000     137.000000
75%              2024-03-02 00:00:00   8556.842500     232.000000
max              2024-08-31 00:00:00  26170.950000     778.000000
std                              NaN   4393.980200     124.024736

Task 2: Apply one missing value strategy and explain why

In [11]:
df_missing = df.copy()
df_missing.loc[0:5, 'Amount'] = np.nan

df_missing['Amount'] = df_missing['Amount'].fillna(df_missing['Amount'].median())

df_missing.isna().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

The median was chosen because it is less sensitive to extreme values compared to the mean.
Since the Amount column may contain outliers, the median provides a more robust replacement for missing values.

Task 3: Detect and handle outliers using IQR

In [12]:
Q1 = df['Amount'].quantile(0.25)
Q3 = df['Amount'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Amount'] < lower) | (df['Amount'] > upper)]
outliers.shape

(50, 6)

In [13]:
df_no_outliers = df[(df['Amount'] >= lower) & (df['Amount'] <= upper)]

print("Original shape:", df.shape)
print("After removing outliers:", df_no_outliers.shape)

Original shape: (3282, 6)
After removing outliers: (3232, 6)

Task 4: Normalize numerical features using Min-Max and Z-score

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_minmax = df[['Amount', 'Boxes Shipped']].copy()

df_minmax[['Amount', 'Boxes Shipped']] = scaler.fit_transform(df_minmax)

df_minmax.head()

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_zscore = df[['Amount', 'Boxes Shipped']].copy()

df_zscore[['Amount', 'Boxes Shipped']] = scaler.fit_transform(df_zscore)

df_zscore.head()

     Amount  Boxes Shipped
0 -0.161686       0.123648
1  0.424660      -0.569868
2 -0.348106      -0.594061
3  1.524058       1.430038
4  1.742345       0.155904

TAsk 5: Apply PCA and interpret explained variance

In [15]:
from sklearn.decomposition import PCA

X = df_zscore[['Amount', 'Boxes Shipped']]

pca = PCA(n_components=2)
principal_components = pca.fit_transform(X)

print("Explained Variance Ratio:", pca.explained_variance_ratio_)

Explained Variance Ratio: [0.50657693 0.49342307]